site_name: Git Open Source Hodler - GOSH
nav:
  - Git Open Source Hodler: index.md
  - On-chain Architecture:
    - GOSH Wallet: on-chain-architecture/gosh-wallet.md
    - Organizations - GOSH DAO and SMV: on-chain-architecture/organizations-gosh-dao-and-smv.md
    - GOSH smart contracts: on-chain-architecture/gosh-smart-contracts.md
  - Working with GOSH:
    - Docker Extension: working-with-gosh/docker-extension.md
    - GOSH Web: working-with-gosh/gosh-web.md
    - Git Remote Helper: working-with-gosh/git-remote-helper.md
    - Build and Sign Images: working-with-gosh/build-and-sign-images.md
    - Verify Images in Docker Extension: working-with-gosh/verify-images-in-docker-extension.md
  - Links:
    - GOSH website: https://gosh.sh/
    - GOSH Web App: https://app.gosh.sh/
    - GOSH Blockchain Explorer: https://gosh.live/
    - GOSH repository: https://github.com/gosh-sh/gosh

markdown_extensions:
    - admonition

theme: 
  # name: readthedocs
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    primary: white
    accent: teal
